[http.middlewares]
 [http.middlewares.chain-no-auth]
  [http.middlewares.chain-no-auth.chain]
    middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers"]

 [http.middlewares.chain-authelia]
  [http.middlewares.chain-authelia.chain]
     middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers", "middlewares-authelia"]
